### ISSUE TITLE
Action listFiles not found.

### ISSUE THREAD

**Issue by jmanhype** [e2b-dev/e2b-cookbook#7]
Action listFiles not found.

using the github developer it wont load correctly please help

**Comment by mlejva** [comment]
Please post here the whole output from your terminal

**Comment by tizkovatereza** [comment]
Hello @jmanhype, my guess is that you are trying to use the JavaScript version if I am correct?
That version of the assistant is still in progress and doesn't have the latest update, but we will update this version soon too.
