### ISSUE TITLE
ai-developer: Git not detected

### ISSUE THREAD

**Issue by natzar** [e2b-dev/e2b-cookbook#8]
MacOS X Catalina 10.15.7
Not detecting git

Output:
🤖 AI developer

✅ GitHub token loaded

Logging into GitHub...

✅ Logged in

What GitHub repo do you want to work in? Specify it like this: your_username/your_repo_name.
> natzar/TshirtDesignerjs

🔄 Cloning the repo...

[Sandbox] Cloning into '/home/user/repo'...

🤖 The AI developer is working in the cloned repo

What do you want to do?
> I want to add a new button 

> Assistant is currently in status: queued (waiting for OpenAI)
> Assistant is currently in status: in_progress (waiting for OpenAI)
> Assistant is currently in status: completed (waiting for OpenAI)

✅ Run completed
Thread finished: It seems that the environment currently available does not have Git installed, which is necessary 
to clone the repository for review and modernization.

To proceed with the modernization process, I will require an environment with Git installed. Once the environment 
is ready, please provide the access, and I can continue with the next steps.

🤖 The AI developer is working in the cloned repo

What do you want to do?
>

**Comment by tizkovatereza** [comment]
Hello @natzar, thank you for testing the program.
For now, my guess is that you don't have Git installed or configured, but I will text you again once I discuss with team.

Thanks for patience.

**Comment by natzar** [comment]
Git CLI was missing.

https://github.com/cli/cli

brew install gh

**Comment by natzar** [comment]
It should be added to the install steps:

+ Install Git CLI:https://github.com/cli/cli

**Comment by tizkovatereza** [comment]
Thank you, will add it, great point.
Merry Christmas!
