### ISSUE TITLE
No access to '/home/user/repo' 

### ISSUE THREAD

**Issue by natzar** [e2b-dev/e2b-cookbook#9]
MACOSX Catalina

$ poetry run start

🤖 AI developer

✅ GitHub token loaded

Logging into GitHub...

✅ Logged in

What GitHub repo do you want to work in? Specify it like this: your_username/your_repo_name.
> natzar/European-Neighborhoods-Json-Coords

🔄 Cloning the repo...

[Sandbox] Cloning into '/home/user/repo'...

🤖 The AI developer is working in the cloned repo

What do you want to do?
> add more neighborhood geo boundaries. Can we add bilbao.json containing neighborhoods and their coordinates like the other cities and files?

> Assistant is currently in status: queued (waiting for OpenAI)
> Assistant is currently in status: in_progress (waiting for OpenAI)
> Assistant is currently in status: completed (waiting for OpenAI)

✅ Run completed
Thread finished: I**t seems that the specified directory '/home/user/repo' does not exist in this environment. In 
order to proceed, I need to have access to the codebase repository**. Could you please provide me with the necessary 
access or share the codebase with me so that I can begin working on adding the Bilbao geo boundary file?

🤖 The AI developer is working in the cloned repo

What do you want to do?
> 

Any workaround?

**Comment by tizkovatereza** [comment]
Hello @natzar, thanks for pointing this out.

Did you give your GitHub token the following permissions?

<img width="600" alt="image" src="https://github.com/e2b-dev/e2b-cookbook/assets/135881365/d098766d-6d9d-44f1-bc27-620599841ceb">

<img width="286" alt="image" src="https://github.com/e2b-dev/e2b-cookbook/assets/135881365/0ea79a3b-af80-4868-a851-83b09caddf67">

<img width="163" alt="image" src="https://github.com/e2b-dev/e2b-cookbook/assets/135881365/5af26900-feed-4c6d-85a5-a563ee4431a2">

**Comment by natzar** [comment]
Creating a new assistant with provided helped, re-using an existing assistant, not.

**Comment by mlejva** [comment]
Yes. It's mentioned in the readme in the steps
